@baseUri=http://localhost:3000/api 

### test
POST {{baseUri}}/test

### generate wallpaper
POST {{baseUri}}/gen-wallpaper
Content-Type: application/json

{
    "description": "coding at sky."
}

### get wallpapers
GET {{baseUri}}/get-wallpapers

### checkout
POST {{baseUri}}/checkout 
Content-Type: application/json

{
    "amount": 990, //付款金额，这里一般用分，网站上是9.9美元，这里就是990
    "plan": "subscribe", //付费策略，这里是订阅模式
    "credits": 50 //送的积分
}